mixed-port: 7890
allow-lan: true
mode: rule
log-level: info
ipv6: true
tcp-concurrent: true
unified-delay: true
profile:
  store-selected: true
  store-fake-ip: true

proxies: []

proxy-groups:
  - name: 🔰 代理
    type: select
    proxies:
      - 自动选择
      - 🎯 直连
  - name: 自动选择
    type: url-test
    proxies: []
    url: https://www.gstatic.com/generate_204
    interval: 300
    tolerance: 50
  - name: 🎯 直连
    type: select
    proxies:
      - DIRECT

rules:
  - GEOIP,CN,🎯 直连
  - MATCH,🔰 代理
